/* ============================================
   Projects data source — single source of truth
   ============================================
   Add / edit projects here. Changes propagate to:
   - projects.html (gallery, search, filters, detail modal)
   - index.html (featured cards, when `featured: true`)

   Fields
   - id          unique slug; also the deep link (projects.html#<id>)
   - title, category (key of CATEGORIES), summary (one line on the card)
   - description long-form text for the modal (\n\n = new paragraph)
   - highlights  bullet list of what was built / what stands out
   - role        what I did on the project
   - team        who built it (Solo, Team of 5, Game Jam team…)
   - date        display label (e.g. "GGJ 2024", "2025")
   - year        number, used for "Newest" sorting (optional)
   - program     gold badge for funding / competitions / theses (optional)
   - stack       tech badges
   - image       cover image; falls back to a generated category cover
   - imageFit    'contain' for portrait / phone screenshots (optional)
   - gallery     extra screenshots shown in the modal viewer
   - videos      YouTube / Vimeo / .mp4 URLs embedded in the modal
   - links       { github, demo, video, doc }
   - featured    show on the home page

   ─── Adding photos ───
   1. Drop images into Assets/projects/<project-id>/
   2. Set  image:   media('<id>', 'cover.webp'),
           gallery: gallery('<id>', ['1.webp', '2.webp']),
   Missing images fail silently.
============================================ */

// Helpers: keep image paths short. Pair with Assets/projects/<id>/ folders.
function media(id, file) {
    return `Assets/projects/${id}/${file}`;
}
function gallery(id, files) {
    return (files || []).map((f) => media(id, f));
}

const CATEGORIES = {
    'games':         { label: 'Games',           icon: 'fa-gamepad',       hue: 265 },
    'engine-tools':  { label: 'Engines & Tools', icon: 'fa-gears',         hue: 190 },
    'ai-ml':         { label: 'AI / ML',         icon: 'fa-robot',         hue: 320 },
    'iot-hardware':  { label: 'IoT / Hardware',  icon: 'fa-microchip',     hue: 150 },
    'mobile':        { label: 'Mobile',          icon: 'fa-mobile-screen', hue: 215 },
    'research':      { label: 'Research',        icon: 'fa-flask',         hue: 35 },
    'academic':      { label: 'Academic',        icon: 'fa-graduation-cap', hue: 240 },
    'leadership':    { label: 'Leadership',      icon: 'fa-users',         hue: 170 },
};

const PROJECTS = [
    /* ─── Games ───────────────────────────────────────────── */
    {
        id: 'stratis',
        title: 'Stratis (GP-I)',
        category: 'games',
        program: 'Graduation Project',
        summary: 'Tactical AI simulation in Unity where enemies learn to fight with PPO reinforcement learning.',
        description: 'Stratis is my first graduation project: a Unity-based tactical combat simulation built on ML-Agents. Enemy agents are trained with Proximal Policy Optimization (PPO) and combined with rule-based behaviours, so they can react to the player instead of following fixed scripts.\n\nThe work covers the full loop — building the simulation environment, designing observations and rewards, training the agents and bringing the trained models back into a playable scene.',
        highlights: [
            'Trained enemy agents with PPO using Unity ML-Agents',
            'Hybrid behaviour model: rule-based tactics + learned policies',
            'Real-time perception system (vision / detection) for agents',
            'Shooting mechanics and combat scenarios for training and play',
        ],
        role: 'Designer & developer — environment, agents, training pipeline',
        team: 'Solo',
        date: 'Graduation Project I',
        year: 2025,
        stack: ['Unity', 'C#', 'ML-Agents', 'Reinforcement Learning', 'PPO'],
        image: '', gallery: [],
        links: { github: 'https://github.com/erenatasun/STRATIS' },
        featured: true,
    },
    {
        id: 'this-is-blast',
        title: 'This Is Blast! — Hybrid-Casual Puzzle',
        category: 'games',
        program: 'Studio Case Study',
        summary: 'Presentation-ready mobile puzzle for the roof.games case: 13 solvable levels, 112 unit tests.',
        description: 'A Unity case study inspired by Voodoo\'s "This Is Blast!", built for the roof.games Game Developer Case. Colour-matched cannons are pulled from a 7-lane queue into 5 firing slots and chew through a descending wall of blocks; three cannons of one colour merge into one.\n\nThe brief asked for a game that feels presentation-ready rather than a prototype, so the scope is deliberately narrow and the effort went into polish and architecture. The simulation resolves instantly and the visuals only replay outcomes that are already settled — the rules live in an engine-free assembly that is covered by 112 unit tests.',
        highlights: [
            'Engine-free Core assembly (no UnityEngine reference) covered by 112 unit tests',
            'Level generator that builds boards by simulating a winning run — every level is provably solvable',
            'Durable blocks, stones, Shuffle / Recall boosters that never break solvability',
            'Meta layer: lives with timed refill, coins, market',
            '"One property, one owner" animation rule that fixed three real animation bugs',
            'All sprites (SDF) and sound effects generated in code; custom level editor tool',
        ],
        role: 'Solo developer — gameplay, architecture, tools, tests',
        team: 'Solo',
        date: 'roof.games case · 2026',
        year: 2026,
        stack: ['Unity 6', 'C#', 'URP', 'DOTween', 'Unit Testing', 'Android'],
        image: media('this-is-blast', '2.webp'),
        imageFit: 'contain',
        gallery: gallery('this-is-blast', ['1.webp', '2.webp', '3.webp', '4.webp', '5.webp', '6.webp']),
        videos: [],
        links: {
            github: 'https://github.com/erenatasun/Hybrid-CasualPuzzelGame',
            video: 'https://drive.google.com/file/d/1ntuH9Ug8W-y26QE3PgUrSDCYYF41uMAF/view?usp=sharing',
        },
        featured: true,
    },
    {
        id: 'mask-heist',
        title: 'Mask Heist',
        category: 'games',
        summary: 'Online multiplayer heist game from Global Game Jam 2026 — every mask grants a different power.',
        description: 'A networked Unity heist game built during Global Game Jam 2026. Players pick up masks that grant special abilities, sneak around the level, hide loot and try to outplay each other.\n\nNetworking is built on Mirror: mask selection, invisibility and sprint states are synchronised across clients.',
        highlights: [
            'Online multiplayer with Mirror (SyncVars, NetworkBehaviours)',
            'Mask ability system: invisibility, decoy clone, scanner, tracker, sprinter, disruptor, silent',
            'Loot pool, hideable items and spawn-point management',
            'Energy-bar based ability balancing',
        ],
        role: 'Gameplay & network programmer',
        team: 'Game Jam team',
        date: 'GGJ 2026',
        year: 2026,
        stack: ['Unity', 'C#', 'Mirror', 'Multiplayer', 'GGJ 2026'],
        image: '', gallery: [],
        links: { github: 'https://github.com/erenatasun/MaskHeist' },
        featured: false,
    },
    {
        id: 'wordswipe',
        title: 'WordSwipe',
        category: 'games',
        program: 'Studio Case Study',
        summary: 'Swipe-based mobile word puzzle built for a Playable Studios case study.',
        description: 'A mobile word puzzle inspired by popular swipe-based word games. Players connect letters on a wheel to discover hidden words and complete each level.\n\nRather than only recreating the mechanic, the goal was a scalable foundation that can easily take new levels and features — clean architecture and reusable systems first.',
        highlights: [
            'Swipe-based letter selection with smooth, responsive input',
            'Hidden-word crossword board with progressive levels',
            'Hint system and shuffle',
            'Modular, scalable project architecture',
        ],
        role: 'Solo developer',
        team: 'Solo',
        date: 'Playable Studios case · 2026',
        year: 2026,
        stack: ['Unity', 'C#', 'TextMeshPro', 'Mobile UI'],
        image: media('wordswipe', '1.webp'),
        imageFit: 'contain',
        gallery: gallery('wordswipe', ['1.webp', '2.webp']),
        links: { github: 'https://github.com/erenatasun/WordSwipe' },
        featured: false,
    },
    {
        id: 'web-project-game',
        title: 'Web Multiplayer Game',
        category: 'games',
        summary: 'Browser-playable Unity game with matchmaking queue and character selection over WebSockets.',
        description: 'A Unity WebGL project exploring online play in the browser. Players join a matchmaking queue, get matched by the server and pick their characters before the match starts. Networking runs on Mirror with the SimpleWeb (WebSocket) transport so it works from a web build.',
        highlights: [
            'Server-side matchmaking queue with match-found messages',
            'Character selection flow and main menu UI',
            'Mirror networking over WebSockets for WebGL builds',
        ],
        role: 'Developer',
        team: 'Solo',
        date: '2025',
        year: 2025,
        stack: ['Unity', 'C#', 'WebGL', 'Mirror', 'WebSockets'],
        image: '', gallery: [],
        links: { github: 'https://github.com/erenatasun/WebProjectGame' },
        featured: false,
    },
    {
        id: 'bubble-galaxy-defense',
        title: 'Bubble Galaxy Defense',
        category: 'games',
        summary: 'Pixel-art space defense: protect your ship with a bubble shield against incoming waves.',
        description: 'A 2D pixel-art defense game set in a stylised galaxy. The player runs around the ship, collects scrap and keeps the bubble shield up while enemy waves close in. Built by a team of three with a full game design document.',
        highlights: [
            'Enemy waves with progressive difficulty',
            'Four-way character movement, dash and ammo management',
            'Shield / base defense core loop, menus and game-over flow',
            'Planned and tracked through a written Game Design Document',
        ],
        role: 'Project manager & developer',
        team: 'Team of 3',
        date: '2025',
        year: 2025,
        stack: ['Unity', 'C#', '2D', 'Pixel Art'],
        image: media('bubble-galaxy-defense', '1.webp'),
        gallery: gallery('bubble-galaxy-defense', ['1.webp', '3.webp', '4.webp', '5.webp', '2.webp']),
        links: {
            github: 'https://github.com/erenatasun/BubbleGalaxyDefense',
            doc: 'https://docs.google.com/document/d/1JPuRjllGyEGflPVad8bCkjMTMehuycp0mXtrS4YxtAM/edit?usp=sharing',
        },
        featured: false,
    },
    {
        id: 'ecovado-bee-savior',
        title: 'Ecovado: Bee Savior',
        category: 'games',
        summary: '3D third-person eco adventure — a hero avocado saves poisoned bees. Built in 3 Scrum sprints.',
        description: 'Join the hero avocado on a mission to rescue bees from ill-intentioned growers: find antidotes for poisoned bees, solve puzzles and restore nature\'s balance. A 3D third-person adventure / puzzle game made by a team of five during the Oyun ve Uygulama Akademisi bootcamp.\n\nThe project was run with Scrum over three sprints — backlog in Trello, daily scrums, sprint reviews and retrospectives documented in the repository.',
        highlights: [
            'Three-level 3D adventure with puzzles and an AI-opponent puzzle finale',
            'Dialogue system, bee and mole NPC behaviour with NavMesh',
            'Character animations: climbing, swinging, carrying, falling',
            'Scrum process: 3 sprints, 50-point backlog, Trello board',
        ],
        role: 'Product Owner & developer',
        team: 'Team of 5 (Echo Team)',
        date: 'OUA Bootcamp · 2024',
        year: 2024,
        stack: ['Unity', 'C#', '3D', 'NavMesh', 'Scrum'],
        image: media('ecovado-bee-savior', '2.webp'),
        gallery: gallery('ecovado-bee-savior', ['1.webp', '2.webp', '4.webp', '3.webp', '5.webp', '6.webp']),
        links: { github: 'https://github.com/erenatasun/EcovadoBeeSavior' },
        featured: true,
    },
    {
        id: 'fiasco-circus',
        title: 'Fiasco Circus',
        category: 'games',
        summary: 'Dark, whimsical take on "Make Me Laugh" — Global Game Jam entry with hand-made pixel art.',
        description: 'Fiasco Circus is a dark and whimsical game developed at Global Game Jam, hosted at İzmir Ekonomi Üniversitesi. The jam theme was "Make Me Laugh" — we took it in a darker direction.\n\nBesides programming and asset integration, I created most of the character designs and animations in Aseprite and helped drive project decisions within the team.',
        highlights: [
            'Most character designs and animations drawn in Aseprite',
            'Asset integration and gameplay programming',
            'Project management and key design decisions in a jam team',
        ],
        role: 'Developer, character artist & animator',
        team: 'Game Jam team',
        date: 'GGJ 2024',
        year: 2024,
        stack: ['Unity', 'C#', 'Aseprite', 'Pixel Art', 'GGJ'],
        image: media('fiasco-circus', '1.webp'),
        gallery: gallery('fiasco-circus', ['1.webp', '6.webp', '3.gif', '4.gif', '2.webp', '5.webp']),
        links: { github: 'https://github.com/erenatasun/Fiasco_Circus' },
        featured: false,
    },
    {
        id: 'subway-surfers-clone',
        title: 'Subway Surfers-Style Runner',
        category: 'games',
        summary: 'Mechanically complete endless runner — Velo Games internship project.',
        description: 'An endless runner in the style of Subway Surfers, delivered during my Velo Games Studios internship under the mentorship of senior developer Tolga Karanlıkoğlu. The focus was on building the game mechanics completely and robustly, with the UI kept intentionally simple.',
        highlights: [
            'Lane switching, jumping and obstacle avoidance',
            'Procedural obstacle generation and scoring loop',
            'High-score tracking and restart flow',
        ],
        role: 'Game developer intern',
        team: 'Mentored',
        date: 'Velo Games · 2024',
        year: 2024,
        stack: ['Unity', 'C#', 'Endless Runner', '3D'],
        image: media('subway-surfers-clone', '2.webp'),
        gallery: gallery('subway-surfers-clone', ['1.webp', '2.webp', '3.webp', '4.webp']),
        links: { github: 'https://github.com/erenatasun/SubwaySurfersClone' },
        featured: false,
    },
    {
        id: 'tappy-fish',
        title: 'Tappy Fish',
        category: 'games',
        summary: 'Tap-to-swim arcade game — one of my first complete Unity games.',
        description: 'One of my first game development projects, made to learn core game mechanics end to end. The player guides a fish between obstacles; it is easy to pick up but gets harder the longer you survive.',
        highlights: [
            'Tap controls with tuned jump feel',
            'Difficulty that ramps up over time',
            'Score, medals and high-score tracking',
        ],
        role: 'Solo developer',
        team: 'Solo',
        date: '2024',
        year: 2024,
        stack: ['Unity', 'C#', '2D', 'Hyper-Casual'],
        image: media('tappy-fish', '4.webp'),
        imageFit: 'contain',
        gallery: gallery('tappy-fish', ['4.webp', '3.webp', '1.webp', '2.webp']),
        links: { github: 'https://github.com/erenatasun/TappyFish' },
        featured: false,
    },
    {
        id: 'earthquake-game',
        title: 'Earthquake Game',
        category: 'games',
        summary: 'Earthquake-awareness prototype — can a game teach what to do when the ground shakes?',
        description: 'A Unity prototype built around earthquake-awareness scenarios, exploring how game mechanics can carry an educational message.',
        highlights: ['Scenario-based gameplay with an educational goal'],
        role: 'Developer',
        team: 'Solo',
        date: '2024',
        year: 2024,
        stack: ['Unity', 'C#', 'Serious Games'],
        image: '', gallery: [],
        links: { github: 'https://github.com/erenatasun/EarthquakeGame' },
        featured: false,
    },
    {
        id: 'ouagj24',
        title: 'OUA Game Jam 2024',
        category: 'games',
        summary: '2D action platformer for the Oyun ve Uygulama Akademisi Game Jam.',
        description: 'A 2D platformer built for the OUA Game Jam 2024 under jam time constraints — shooting enemies, fall damage, a lives system and multi-scene progression.',
        highlights: [
            'Character controller, fall damage and lives system',
            'Shooting enemies with projectiles',
            'Score tracking and scene-to-scene progression',
        ],
        role: 'Developer',
        team: 'Game Jam team',
        date: 'OUA Jam 2024',
        year: 2024,
        stack: ['Unity', 'C#', '2D', 'Game Jam'],
        image: '', gallery: [],
        links: { github: 'https://github.com/erenatasun/OUAGJ24' },
        featured: false,
    },
    {
        id: 'baytar-pyng',
        title: 'Baytar PYNG',
        category: 'games',
        summary: 'Game-jam top-down shooter mixing base defense with towers and pickups.',
        description: 'A game-jam entry built collaboratively with a small team. The player aims with a crosshair, defends a base alongside towers and collects pickups while enemies spawn in waves.',
        highlights: [
            'Crosshair aiming and player combat',
            'Enemy spawner, towers and base health',
            'Pickups and end-point / win conditions',
        ],
        role: 'Gameplay programmer',
        team: 'Game Jam team',
        date: 'Game Jam · 2024',
        year: 2024,
        stack: ['Unity', 'C#', '2D', 'Game Jam'],
        image: '', gallery: [],
        links: { github: 'https://github.com/erenatasun/Baytar_PYNG' },
        featured: false,
    },
    {
        id: 'fancy-platform',
        title: 'Fancy Platform',
        category: 'games',
        summary: '2D platformer focused on tight movement and feel.',
        description: 'A 2D Unity platformer prototype built to practise tight movement, level design and core platformer mechanics.',
        highlights: ['Responsive player controller', 'Hand-built practice levels'],
        role: 'Solo developer',
        team: 'Solo',
        date: '2024',
        year: 2024,
        stack: ['Unity', 'C#', '2D Platformer'],
        image: '', gallery: [],
        links: { github: 'https://github.com/erenatasun/fancy_platform' },
        featured: false,
    },
    {
        id: 'aircraft-shooter',
        title: 'Aircraft Shooter',
        category: 'games',
        summary: 'Space Invaders-style shooter with a mothership, shields, pickups and object pooling.',
        description: 'A Unity arcade shooter in the spirit of Space Invaders. Alien formations advance while a mothership passes overhead; the player uses shields, pickups and an inventory to survive.',
        highlights: [
            'Alien formation controller and mothership',
            'Object pooling for bullets and effects',
            'Shields, pickups, inventory and ship stats',
        ],
        role: 'Solo developer',
        team: 'Solo',
        date: '2023',
        year: 2023,
        stack: ['Unity', 'C#', 'Object Pooling', 'Shaders'],
        image: '', gallery: [],
        links: { github: 'https://github.com/erenatasun/AircraftShooterGame' },
        featured: false,
    },
    {
        id: '3d-runner',
        title: '3D Runner',
        category: 'games',
        summary: 'Early 3D runner prototype — lane movement and a follow camera.',
        description: 'A 3D Unity runner prototype built to explore lane-based movement, a smooth follow camera and character animation.',
        highlights: ['Player controller and follow camera', 'Animated 3D character'],
        role: 'Solo developer',
        team: 'Solo',
        date: '2023',
        year: 2023,
        stack: ['Unity', 'C#', '3D'],
        image: '', gallery: [],
        links: { github: 'https://github.com/erenatasun/3D-Runner' },
        featured: false,
    },

    /* ─── Engines & Tools ─────────────────────────────────── */
    {
        id: 'custom-2d-engine',
        title: 'MakeMyEngine — C++ 2D Engine',
        category: 'engine-tools',
        summary: 'Lightweight 2D game engine written from scratch in modern C++ and OpenGL.',
        description: 'MakeMyEngine is a lightweight 2D engine / skeleton built with modern C++ and OpenGL. It combines tilemaps, sprite rendering, AABB collisions, a simple UI and input handling, with rendering, scene, collision and input separated into clear, modular systems.\n\nThe goal: cut the "setup from scratch" overhead for prototypes while staying readable enough to learn engine design from. The demo scene is a Pong game running entirely on the engine.',
        highlights: [
            'Orthographic camera + controller, 2D renderer and GLSL shader pipeline',
            'Entity / Component architecture (Sprite, Velocity, Paddle components…)',
            'AABB collision system and keyboard input layer',
            'CSV-based tilemaps and an asset manager',
            'CMake build; roadmap: batching, particles, audio, scripting',
        ],
        role: 'Solo developer — architecture and implementation',
        team: 'Solo',
        date: '2025',
        year: 2025,
        stack: ['C++', 'OpenGL', 'GLSL', 'GLFW', 'CMake', 'ECS'],
        image: media('custom-2d-engine', '1.webp'),
        gallery: gallery('custom-2d-engine', ['1.webp', '2.webp', '3.webp']),
        links: { github: 'https://github.com/erenatasun/MyGameEngine' },
        featured: true,
    },
    {
        id: 'webgl-letter-transformations',
        title: 'WebGL 2D Letter Transformations',
        category: 'engine-tools',
        summary: 'Letters built from raw triangles and transformed live with custom shaders.',
        description: 'A midterm project for the CSE 3219 Computer Graphics course (Spring 2025). The letters "E" and "A" are modelled by hand from triangle vertices and manipulated in real time through custom vertex and fragment shaders driven by UI sliders.',
        highlights: [
            'Triangle-based shape modelling from vec2 vertices',
            'Vertex shader for translation / scaling, fragment shader for colour',
            'Slider UI for position, scale and RGB colour',
            '"A" is always rendered in the inverse colour of "E"',
        ],
        role: 'Solo developer',
        team: 'Coursework',
        date: 'CSE 3219 · 2025',
        year: 2025,
        stack: ['JavaScript', 'WebGL', 'GLSL', 'HTML/CSS'],
        image: '', gallery: [],
        links: { github: 'https://github.com/erenatasun/WebGL_2D_Letter_Transformations' },
        featured: false,
    },

    /* ─── AI / ML ─────────────────────────────────────────── */
    {
        id: 'tania',
        title: 'TanIA — AI Healthcare Assistant',
        category: 'ai-ml',
        program: 'TEKNOFEST',
        summary: 'NLP-powered assistant that gives preliminary assessments and physician referrals.',
        description: 'TEKNOFEST project: I led end-to-end development of an NLP-driven healthcare assistant. From the patient\'s own description of their symptoms it produces a preliminary assessment and recommends which kind of physician to see.',
        highlights: [
            'Natural-language symptom input',
            'Preliminary assessment and personalised physician referral',
            'Led the project end to end',
        ],
        role: 'Project lead & developer',
        team: 'Team',
        date: 'TEKNOFEST',
        stack: ['Python', 'NLP', 'Machine Learning'],
        image: '', gallery: [],
        links: {},
        featured: true,
    },
    {
        id: 'air-defense',
        title: 'AI-Controlled Air Defense System',
        category: 'ai-ml',
        program: 'TEKNOFEST',
        summary: 'Laser-based autonomous defense with AI target recognition and multi-sensor fusion.',
        description: 'TEKNOFEST project: an autonomous laser-based defense system that combines AI-driven target recognition with multi-sensor fusion to detect and neutralise aerial threats within a 10-metre engagement radius.',
        highlights: [
            'AI-based target recognition',
            'Multi-sensor fusion for detection',
            '10 m engagement radius',
        ],
        role: 'System design & AI',
        team: 'Team',
        date: 'TEKNOFEST',
        stack: ['AI', 'Computer Vision', 'Sensor Fusion', 'Laser'],
        image: '', gallery: [],
        links: {},
        featured: false,
    },
    {
        id: 'nlp-project',
        title: 'NLP Project — Custom Language',
        category: 'ai-ml',
        summary: 'A constructed language designed with NLP techniques in Java.',
        description: 'A Java project exploring the design of a new language with NLP-driven rules — tokenisation, grammar and semantics built from first principles.',
        highlights: ['Tokeniser and grammar rules', 'Semantics defined from first principles'],
        role: 'Solo developer',
        team: 'Solo',
        date: '2024',
        year: 2024,
        stack: ['Java', 'NLP'],
        image: '', gallery: [],
        links: { github: 'https://github.com/erenatasun/NLPProject' },
        featured: false,
    },

    /* ─── IoT / Hardware ──────────────────────────────────── */
    {
        id: 'smart-solar-panel',
        title: 'Smart Solar Panel',
        category: 'iot-hardware',
        program: 'TÜBİTAK 2209-A',
        summary: 'Funded IoT solar panel that re-orients itself in real time using weather data.',
        description: 'A research project funded under TÜBİTAK\'s 2209-A University Students Research Projects programme. The IoT-driven panel ingests real-time meteorological data and adjusts its orientation with adaptive positioning algorithms to maximise energy yield.',
        highlights: [
            'Real-time meteorological data ingestion',
            'Adaptive positioning algorithm for panel orientation',
            'Sensor + embedded control integration',
            'Funded by TÜBİTAK 2209-A',
        ],
        role: 'Researcher & developer',
        team: 'Team',
        date: 'TÜBİTAK 2209-A',
        stack: ['IoT', 'Python', 'Sensors', 'Embedded', 'Research'],
        image: '', gallery: [],
        links: {},
        featured: true,
    },

    /* ─── Mobile ──────────────────────────────────────────── */
    {
        id: 'community-event-app',
        title: 'UniClub — Community Events App',
        category: 'mobile',
        summary: 'Flutter app that keeps students on top of university club events.',
        description: 'A Flutter application that highlights and organises events hosted by university student communities, so students never miss a chance to take part and connect.',
        highlights: [
            'Highlighted events at the top of the home page',
            'Interactive calendar view',
            'Per-community pages with mission, past and upcoming events',
            'Reminders for saved / favourite events',
        ],
        role: 'Solo developer',
        team: 'Solo',
        date: '2024',
        year: 2024,
        stack: ['Flutter', 'Dart', 'Firebase'],
        image: media('community-event-app', '3.webp'),
        imageFit: 'contain',
        gallery: gallery('community-event-app', ['3.webp', '1.webp', '4.webp', '2.webp']),
        links: { github: 'https://github.com/erenatasun/uniclub' },
        featured: false,
    },
    {
        id: 'firplus-calorie',
        title: 'FirPlus — Calorie Tracker',
        category: 'mobile',
        summary: 'Flutter calorie tracker with streaks, charts and AI-ready photo meal logging.',
        description: 'A Flutter app for tracking daily calorie intake. Meals are stored locally with Hive; a dashboard shows progress rings, charts and streaks to keep users motivated. An AI service layer is prepared for photo-based food recognition.',
        highlights: [
            'Meal logging with local Hive database',
            'Calorie progress ring, fl_chart charts and calendar history',
            'Streak system with flame widget',
            'AI service layer for photo-based food analysis',
        ],
        role: 'Solo developer',
        team: 'Solo',
        date: '2026',
        year: 2026,
        stack: ['Flutter', 'Dart', 'Hive', 'Provider'],
        image: '', gallery: [],
        links: { github: 'https://github.com/erenatasun/FirPlus' },
        featured: false,
    },
    {
        id: 'pet-adopting-app',
        title: 'Online Pet Adopting App',
        category: 'mobile',
        summary: 'Flutter app connecting adopters, shelters and admins — SWE group project.',
        description: 'A Flutter application built as a Software Engineering group project. Adopters browse pets and apply; shelters list pets and review applications; admins oversee the platform. I collaborated on the architecture and feature delivery.',
        highlights: [
            'Three roles: adopter, shelter, admin — each with its own dashboard',
            'Adoption application and review flow',
            'Notifications, profiles, onboarding',
            'Provider-based state management and service layer',
        ],
        role: 'Developer',
        team: 'SWE Group Project',
        date: '2026',
        year: 2026,
        stack: ['Flutter', 'Dart', 'Provider'],
        image: '', gallery: [],
        links: { github: 'https://github.com/erenatasun/OnlinePetAdoptingApp' },
        featured: false,
    },

    /* ─── Research ────────────────────────────────────────── */
    {
        id: 'tusas-lift-up',
        title: 'TUSAŞ Lift Up (GP-II)',
        category: 'research',
        program: 'Graduation Project',
        summary: 'Digital Image Correlation software that detects cracks in fatigue-test data.',
        description: 'Graduation project (GP-II) within the TUSAŞ Lift Up programme: Digital Image Correlation (DIC) based software that analyses multiple crack-detection indicators across fatigue-test datasets and validates detection accuracy against empirical material-failure data.',
        highlights: [
            'DIC-based analysis of fatigue-test image data',
            'Multiple crack-detection indicators compared',
            'Validated against empirical failure data',
        ],
        role: 'Developer & researcher',
        team: 'Team',
        date: 'Graduation Project II',
        year: 2026,
        stack: ['Python', 'DIC', 'Image Processing', 'Fatigue Analysis'],
        image: '', gallery: [],
        links: {},
        featured: false,
    },
    {
        id: 'numerical-fixed-point',
        title: 'Numerical Fixed-Point Methods',
        category: 'research',
        summary: 'Fixed-point iteration solver with JSON I/O, error tracking and plots.',
        description: 'A Python implementation of the Fixed Point Iteration method for approximating roots of equations. Parameters are read from JSON, every iteration step and its error is logged, and results are written back to JSON and plotted — all behind a simple desktop UI.',
        highlights: [
            'JSON-based input and output',
            'Per-iteration error tracking and convergence check',
            'Iteration plot export',
        ],
        role: 'Solo developer',
        team: 'Solo',
        date: '2024',
        year: 2024,
        stack: ['Python', 'Numerical Methods', 'Matplotlib'],
        image: media('numerical-fixed-point', '1.webp'),
        gallery: gallery('numerical-fixed-point', ['1.webp', '2.webp', '3.webp', '4.webp']),
        links: { github: 'https://github.com/erenatasun/NumericalFixedPoint' },
        featured: false,
    },

    /* ─── Academic ────────────────────────────────────────── */
    {
        id: 'dbms-web-interface',
        title: 'DBMS Web Interface',
        category: 'academic',
        summary: 'Web admin for a store database: customers, orders, payments, products and more.',
        description: 'A web-based interface for managing a database management system: categories, customers, deliveries, orders, payments, products and purchases. Built as coursework to practise end-to-end database-driven web applications.',
        highlights: ['CRUD screens for 7 related entities', 'SQL-backed PHP pages'],
        role: 'Developer',
        team: 'Coursework',
        date: '2025',
        year: 2025,
        stack: ['HTML', 'PHP', 'SQL'],
        image: '', gallery: [],
        links: { github: 'https://github.com/erenatasun/DataBaseManagementSystem-Web-Interface' },
        featured: false,
    },
    {
        id: 'library-management-system',
        title: 'Library Management System (C#)',
        category: 'academic',
        summary: 'C# book-library system applying clean OOP and design patterns.',
        description: 'A book-library management system in C#, designed during my Velo Games Studios internship to practise object-oriented design patterns and clean architecture.',
        highlights: ['OOP design patterns', 'Clean, layered architecture'],
        role: 'Solo developer',
        team: 'Solo',
        date: 'Velo Games · 2024',
        year: 2024,
        stack: ['C#', 'OOP', 'Design Patterns'],
        image: '', gallery: [],
        links: { github: 'https://github.com/erenatasun/LibraryManagementSystem' },
        featured: false,
    },
    {
        id: 'shopping-application',
        title: 'Shopping Application (Java)',
        category: 'academic',
        summary: 'Java OOP shopping application — coursework practice.',
        description: 'A Java shopping application built as coursework practice for object-oriented programming and basic data modelling.',
        highlights: ['Object-oriented data model'],
        role: 'Solo developer',
        team: 'Solo',
        date: '2024',
        year: 2024,
        stack: ['Java', 'OOP'],
        image: '', gallery: [],
        links: { github: 'https://github.com/erenatasun/ShoppingApplication' },
        featured: false,
    },

    /* ─── Leadership ──────────────────────────────────────── */
    {
        id: 'digital-greening-youth',
        title: 'Digital Greening with Youth',
        category: 'leadership',
        program: 'Erasmus+ KA152-YOU',
        summary: 'International youth mobility project across 4 countries — €24,320 budget.',
        description: 'Erasmus+ KA152-YOU project: I coordinated an international youth mobility programme across 4 countries with a €24,320 budget, driving environmental awareness through digital-transformation workshops and cross-cultural collaboration.',
        highlights: [
            '4 partner countries',
            '€24,320 budget',
            'Digital-transformation workshops on environmental awareness',
        ],
        role: 'Project coordinator',
        team: 'International',
        date: 'Erasmus+ KA152-YOU',
        stack: ['Project Management', 'Erasmus+', 'Cross-cultural'],
        image: '', gallery: [],
        links: {},
        featured: false,
    },
];

window.PORTFOLIO = { CATEGORIES, PROJECTS };
