/* ============================================
   Projects data source — single source of truth
   ============================================
   Add / edit projects here. Changes propagate to:
   - projects.html (gallery + filter)
   - index.html (featured cards, when `featured: true`)

   Optional `program` field renders as a gold badge to highlight
   funding / competition / thesis programs (TÜBİTAK, TEKNOFEST, etc.).
============================================ */

const CATEGORIES = {
    'games':         { label: 'Games',           icon: 'fa-gamepad' },
    'engine-tools':  { label: 'Engines & Tools', icon: 'fa-gears' },
    'ai-ml':         { label: 'AI / ML',         icon: 'fa-robot' },
    'iot-hardware':  { label: 'IoT / Hardware',  icon: 'fa-microchip' },
    'mobile':        { label: 'Mobile',          icon: 'fa-mobile-screen' },
    'research':      { label: 'Research',        icon: 'fa-flask' },
    'academic':      { label: 'Academic',        icon: 'fa-graduation-cap' },
    'leadership':    { label: 'Leadership',      icon: 'fa-users' },
};

const PROJECTS = [
    /* ─── Games ───────────────────────────────────────────── */
    {
        id: 'stratis',
        title: 'Stratis (GP-I)',
        category: 'games',
        program: 'Graduation Project',
        summary: 'Unity tactical AI simulation trained with PPO reinforcement learning.',
        description: 'Graduation project: a Unity-based tactical AI simulation built on ML-Agents using Proximal Policy Optimization (PPO). Implemented real-time perception systems, shooting mechanics, and a hybrid rule-based + RL enemy behavior model that adapts to dynamic combat scenarios.',
        stack: ['Unity', 'C#', 'ML-Agents', 'Reinforcement Learning', 'PPO'],
        image: '', gallery: [],
        links: { github: 'https://github.com/erenatasun/STRATIS' },
        featured: true,
        date: 'Graduation Project I',
        team: 'Solo',
    },
    {
        id: 'mask-heist',
        title: 'Mask Heist',
        category: 'games',
        summary: 'Heist-themed game built for Global Game Jam 2026.',
        description: 'A Unity heist game built within the Global Game Jam 2026 window — designed core mechanics and shipped a playable build with a small team under tight time constraints.',
        stack: ['Unity', 'C#', 'GGJ 2026'],
        image: '', gallery: [],
        links: { github: 'https://github.com/erenatasun/MaskHeist' },
        featured: false,
        date: 'GGJ 2026',
        team: 'Game Jam team',
    },
    {
        id: 'wordswipe',
        title: 'WordSwipe',
        category: 'games',
        summary: 'Word-swipe puzzle — Playable Studios case study in plain JavaScript.',
        description: 'A web-based word-swipe puzzle built as a Playable Studios case study. Implemented swipe input, scoring, and a clean rendering loop in vanilla JavaScript with no framework.',
        stack: ['JavaScript', 'HTML5 Canvas', 'Case Study'],
        image: '', gallery: [],
        links: { github: 'https://github.com/erenatasun/WordSwipe' },
        featured: false,
        date: '2026',
        team: 'Solo',
    },
    {
        id: 'web-project-game',
        title: 'Web Project Game',
        category: 'games',
        summary: 'Unity-based web game build for a portfolio / coursework project.',
        description: 'A Unity game packaged for the web — focused on a tight gameplay loop and clean code structure for evaluation.',
        stack: ['Unity', 'C#', 'WebGL'],
        image: '', gallery: [],
        links: { github: 'https://github.com/erenatasun/WebProjectGame' },
        featured: false,
        date: '2025',
        team: 'Solo',
    },
    {
        id: 'bubble-galaxy-defense',
        title: 'Bubble Galaxy Defense',
        category: 'games',
        summary: 'Galaxy-themed defense / shooter built in Unity.',
        description: 'A Unity defense-style shooter set in a stylized galaxy. Implemented enemy waves, shooting mechanics and progressive difficulty scaling.',
        stack: ['Unity', 'C#'],
        image: '', gallery: [],
        links: { github: 'https://github.com/erenatasun/BubbleGalaxyDefense' },
        featured: false,
        date: '2025',
        team: 'Solo',
    },
    {
        id: 'tappy-fish',
        title: 'Tappy Fish',
        category: 'games',
        summary: 'Hyper-casual tap-to-swim prototype (Panteon-style production exercise).',
        description: 'A hyper-casual swimming prototype built as a Panteon-style production exercise. Focus on tight input feel, juice and a fast iteration loop.',
        stack: ['Unity', 'C#', 'Hyper-Casual'],
        image: '', gallery: [],
        links: { github: 'https://github.com/erenatasun/TappyFish' },
        featured: false,
        date: '2024',
        team: 'Solo',
    },
    {
        id: 'fiasco-circus',
        title: 'Fiasco Circus',
        category: 'games',
        summary: 'Chaotic circus-themed entry for Global Game Jam 2024.',
        description: 'A Unity game-jam entry built for Global Game Jam 2024 with a small team — designed and shipped a playable circus-themed game under jam time pressure.',
        stack: ['Unity', 'C#', 'GGJ 2024'],
        image: '', gallery: [],
        links: { github: 'https://github.com/erenatasun/Fiasco_Circus' },
        featured: false,
        date: 'GGJ 2024',
        team: 'Game Jam team',
    },
    {
        id: 'subway-surfers-clone',
        title: 'Subway Surfers-Style Clone',
        category: 'games',
        summary: 'Endless-runner prototype — Velo Games internship.',
        description: 'An endless-runner prototype delivered during my Velo Games Studios internship under the mentorship of senior developer Tolga Karanlıkoğlu. Implemented lane switching, obstacle generation and the scoring loop.',
        stack: ['Unity', 'C#', 'Endless Runner'],
        image: '', gallery: [],
        links: { github: 'https://github.com/erenatasun/SubwaySurfersClone' },
        featured: false,
        date: 'Velo Games · 2024',
        team: 'Mentorship',
    },
    {
        id: 'ecovado-bee-savior',
        title: 'Ecovado Bee Savior',
        category: 'games',
        summary: 'Eco-themed Unity game — rescue the bees.',
        description: 'A team-built Unity game with an environmental awareness theme where the player rescues bees. Contributed to gameplay logic and shader-driven visual integration.',
        stack: ['Unity', 'C#', 'Shaders'],
        image: '', gallery: [],
        links: { github: 'https://github.com/erenatasun/EcovadoBeeSavior' },
        featured: false,
        date: '2024',
        team: 'Team',
    },
    {
        id: 'earthquake-game',
        title: 'Earthquake Game',
        category: 'games',
        summary: 'Earthquake-awareness Unity prototype.',
        description: 'A Unity prototype built around earthquake-awareness scenarios — exploring how game mechanics can carry an educational message.',
        stack: ['Unity', 'C#'],
        image: '', gallery: [],
        links: { github: 'https://github.com/erenatasun/EarthquakeGame' },
        featured: false,
        date: '2024',
        team: 'Solo',
    },
    {
        id: 'ouagj24',
        title: 'OUA Game Jam 2024',
        category: 'games',
        summary: 'Entry for the Oyun ve Uygulama Akademisi Game Jam 2024.',
        description: 'A Unity game-jam entry built for the OUA Game Jam 2024. Designed and shipped under jam time constraints.',
        stack: ['Unity', 'C#', 'Game Jam'],
        image: '', gallery: [],
        links: { github: 'https://github.com/erenatasun/OUAGJ24' },
        featured: false,
        date: 'OUA Jam 2024',
        team: 'Game Jam team',
    },
    {
        id: 'fancy-platform',
        title: 'Fancy Platform',
        category: 'games',
        summary: '2D platformer focused on tight movement and feel.',
        description: 'A 2D Unity platformer prototype built to practice tight movement, level design, and core platformer mechanics.',
        stack: ['Unity', 'C#', '2D Platformer'],
        image: '', gallery: [],
        links: { github: 'https://github.com/erenatasun/fancy_platform' },
        featured: false,
        date: '2024',
        team: 'Solo',
    },
    {
        id: 'baytar-pyng',
        title: 'Baytar PYNG',
        category: 'games',
        summary: 'Game-jam entry — collaborative Unity build.',
        description: 'A game-jam entry built collaboratively with a small team. Contributed to gameplay implementation under jam time pressure.',
        stack: ['Unity', 'C#', 'Game Jam'],
        image: '', gallery: [],
        links: { github: 'https://github.com/erenatasun/Baytar_PYNG' },
        featured: false,
        date: 'Game Jam · 2024',
        team: 'Game Jam team',
    },
    {
        id: 'aircraft-shooter',
        title: 'Aircraft Shooter',
        category: 'games',
        summary: 'Top-down aircraft shooter with shader-driven visuals.',
        description: 'A Unity top-down aircraft shooter with shader-driven visual effects. Implemented enemy spawning, projectile systems and the core combat loop.',
        stack: ['Unity', 'C#', 'Shaders'],
        image: '', gallery: [],
        links: { github: 'https://github.com/erenatasun/AircraftShooterGame' },
        featured: false,
        date: '2023',
        team: 'Solo',
    },
    {
        id: '3d-runner',
        title: '3D Runner',
        category: 'games',
        summary: 'Endless-runner-style 3D Unity prototype.',
        description: 'An endless-runner 3D prototype built in Unity to explore lane-based movement and obstacle generation.',
        stack: ['Unity', 'C#', '3D'],
        image: '', gallery: [],
        links: { github: 'https://github.com/erenatasun/3D-Runner' },
        featured: false,
        date: '2023',
        team: 'Solo',
    },

    /* ─── Engines & Tools ─────────────────────────────────── */
    {
        id: 'custom-2d-engine',
        title: 'Custom 2D Game Engine',
        category: 'engine-tools',
        summary: 'A lightweight 2D game engine written from scratch in C++ with an ECS core.',
        description: 'Personal project: architected and built a 2D game engine from the ground up in C++. Implemented a rendering pipeline, input handling, collision detection, and a data-driven Entity-Component-System (ECS) architecture — focusing on clean abstractions and runtime performance.',
        stack: ['C++', 'ECS', 'Rendering', 'Game Engine'],
        image: '', gallery: [],
        links: { github: 'https://github.com/erenatasun/MyGameEngine' },
        featured: true,
        date: 'Personal Project',
        team: 'Solo',
    },
    {
        id: 'webgl-letter-transformations',
        title: 'WebGL 2D Letter Transformations',
        category: 'engine-tools',
        summary: 'Interactive WebGL demo — vertex-based letters with shader-driven transforms.',
        description: 'A WebGL project demonstrating vertex-based shape modeling, shader usage, and dynamic 2D transformations driven by UI sliders. A hands-on study of the graphics pipeline.',
        stack: ['JavaScript', 'WebGL', 'Shaders'],
        image: '', gallery: [],
        links: { github: 'https://github.com/erenatasun/WebGL_2D_Letter_Transformations' },
        featured: false,
        date: '2025',
        team: 'Solo',
    },

    /* ─── AI / ML ─────────────────────────────────────────── */
    {
        id: 'tania',
        title: 'TanIA — AI Healthcare Assistant',
        category: 'ai-ml',
        program: 'TEKNOFEST',
        summary: 'NLP-powered diagnostic assistant providing preliminary assessments and physician referrals.',
        description: 'TEKNOFEST project: led end-to-end development of an NLP-driven healthcare assistant that delivers preliminary medical assessments and personalized physician referral recommendations based on patient input.',
        stack: ['Python', 'NLP', 'Machine Learning'],
        image: '', gallery: [],
        links: {},
        featured: true,
        date: 'TEKNOFEST',
        team: 'Team',
    },
    {
        id: 'air-defense',
        title: 'AI-Controlled Air Defense System',
        category: 'ai-ml',
        program: 'TEKNOFEST',
        summary: 'Laser-based autonomous defense with AI target recognition and multi-sensor fusion.',
        description: 'TEKNOFEST project: designed an autonomous laser-based defense system that integrates AI-driven target recognition with multi-sensor fusion to detect and neutralize aerial threats within a 10-meter engagement radius.',
        stack: ['AI', 'Computer Vision', 'Sensor Fusion', 'Laser'],
        image: '', gallery: [],
        links: {},
        featured: false,
        date: 'TEKNOFEST',
        team: 'Team',
    },
    {
        id: 'nlp-project',
        title: 'NLP Project — Custom Language',
        category: 'ai-ml',
        summary: 'A constructed language designed with NLP techniques in Java.',
        description: 'A Java project exploring the design of a new language with NLP-driven rules — tokenization, grammar and semantics built from first principles.',
        stack: ['Java', 'NLP'],
        image: '', gallery: [],
        links: { github: 'https://github.com/erenatasun/NLPProject' },
        featured: false,
        date: '2024',
        team: 'Solo',
    },

    /* ─── IoT / Hardware ──────────────────────────────────── */
    {
        id: 'smart-solar-panel',
        title: 'Smart Solar Panel',
        category: 'iot-hardware',
        program: 'TÜBİTAK 2209-A',
        summary: 'TÜBİTAK 2209-A funded IoT solar panel that adapts orientation in real time using meteorological data.',
        description: 'TÜBİTAK 2209-A funded research project: an IoT-driven solar panel system that ingests real-time meteorological data and dynamically adjusts panel orientation through adaptive positioning algorithms to maximize energy yield. Funded under TÜBİTAK\'s 2209-A University Students Research Projects programme.',
        stack: ['IoT', 'Python', 'Sensors', 'Embedded', 'Research'],
        image: '', gallery: [],
        links: {},
        featured: true,
        date: 'TÜBİTAK 2209-A',
        team: 'Team',
    },

    /* ─── Mobile ──────────────────────────────────────────── */
    {
        id: 'community-event-app',
        title: 'Community Event Management App',
        category: 'mobile',
        summary: 'Cross-platform Flutter app for university community activities and event scheduling.',
        description: 'A Flutter mobile application prototype (uniclub) for managing university community activities — member coordination, event scheduling and announcements.',
        stack: ['Flutter', 'Dart', 'Firebase'],
        image: '', gallery: [],
        links: { github: 'https://github.com/erenatasun/uniclub' },
        featured: false,
        date: '2024',
        team: 'Solo',
    },
    {
        id: 'firplus-calorie',
        title: 'FirPlus — Calorie Tracker',
        category: 'mobile',
        summary: 'Flutter calorie-tracking mobile app.',
        description: 'A Flutter mobile application for tracking daily calorie intake. Implemented core CRUD flows, persistent storage and a clean UI for daily logging.',
        stack: ['Flutter', 'Dart'],
        image: '', gallery: [],
        links: { github: 'https://github.com/erenatasun/FirPlus' },
        featured: false,
        date: '2026',
        team: 'Solo',
    },
    {
        id: 'pet-adopting-app',
        title: 'Online Pet Adopting App',
        category: 'mobile',
        summary: 'SWE group project — Flutter app for pet adoption listings.',
        description: 'A Flutter mobile application built as a Software Engineering group project: lets users browse, list and request pet adoptions. Collaborated on architecture and feature delivery.',
        stack: ['Flutter', 'Dart'],
        image: '', gallery: [],
        links: { github: 'https://github.com/erenatasun/OnlinePetAdoptingApp' },
        featured: false,
        date: '2026',
        team: 'SWE Group Project',
    },

    /* ─── Research ────────────────────────────────────────── */
    {
        id: 'tusas-lift-up',
        title: 'TUSAŞ Lift Up (GP-II)',
        category: 'research',
        program: 'Graduation Project',
        summary: 'DIC software analyzing crack-detection indicators across fatigue test datasets.',
        description: 'Graduation project (GP-II): developed Digital Image Correlation (DIC) based software that analyzes multiple crack detection indicators across fatigue test datasets, validating detection accuracy against empirical material failure data.',
        stack: ['DIC', 'Python', 'Image Processing', 'Fatigue Analysis'],
        image: '', gallery: [],
        links: {},
        featured: false,
        date: 'Graduation Project II',
        team: 'Team',
    },
    {
        id: 'numerical-fixed-point',
        title: 'Numerical Fixed-Point Methods',
        category: 'research',
        summary: 'Python implementation and study of fixed-point iteration numerical methods.',
        description: 'A Python project exploring fixed-point iteration as a numerical-methods technique — implementation, convergence study, and validation across sample problems.',
        stack: ['Python', 'Numerical Methods'],
        image: '', gallery: [],
        links: { github: 'https://github.com/erenatasun/NumericalFixedPoint' },
        featured: false,
        date: '2024',
        team: 'Solo',
    },

    /* ─── Academic ────────────────────────────────────────── */
    {
        id: 'dbms-web-interface',
        title: 'DBMS Web Interface',
        category: 'academic',
        summary: 'Web interface for managing a database system across customers, orders, products and more.',
        description: 'A web-based interface for managing a database management system, handling categories, customers, deliveries, orders, payments, products and purchases. Built as a coursework project to practice end-to-end DB-driven web applications.',
        stack: ['HTML', 'PHP', 'SQL'],
        image: '', gallery: [],
        links: { github: 'https://github.com/erenatasun/DataBaseManagementSystem-Web-Interface' },
        featured: false,
        date: '2025',
        team: 'Coursework',
    },
    {
        id: 'library-management-system',
        title: 'Library Management System (C#)',
        category: 'academic',
        summary: 'C# book-library system applying clean OOP and design patterns.',
        description: 'Designed and implemented a book-library management system in C# during my Velo Games Studios internship — applied object-oriented design patterns and clean architecture principles.',
        stack: ['C#', 'OOP', 'Design Patterns'],
        image: '', gallery: [],
        links: { github: 'https://github.com/erenatasun/LibraryManagementSystem' },
        featured: false,
        date: 'Velo Games · 2024',
        team: 'Solo',
    },
    {
        id: 'shopping-application',
        title: 'Shopping Application (Java)',
        category: 'academic',
        summary: 'Java OOP shopping application — coursework practice.',
        description: 'A Java shopping application built as coursework practice for object-oriented programming and basic data modeling.',
        stack: ['Java', 'OOP'],
        image: '', gallery: [],
        links: { github: 'https://github.com/erenatasun/ShoppingApplication' },
        featured: false,
        date: '2024',
        team: 'Solo',
    },

    /* ─── Leadership ──────────────────────────────────────── */
    {
        id: 'digital-greening-youth',
        title: 'Digital Greening with Youth',
        category: 'leadership',
        program: 'Erasmus+ KA152-YOU',
        summary: 'International Erasmus+ youth mobility project across 4 countries — 24,320 EUR budget.',
        description: 'Erasmus+ KA152-YOU project: coordinated an international youth mobility program across 4 countries with a 24,320 EUR budget. Drove environmental awareness initiatives through digital transformation workshops and cross-cultural collaboration.',
        stack: ['Project Management', 'Erasmus+', 'Cross-cultural'],
        image: '', gallery: [],
        links: {},
        featured: false,
        date: 'Erasmus+ KA152-YOU',
        team: 'International',
    },
];

window.PORTFOLIO = { CATEGORIES, PROJECTS };
